### ISSUE TITLE
The software doesn't work

### ISSUE THREAD

**Issue by CloneHub94** [nowakowsky/PokerStars#2]
Dear nowakowsky,

I tested out this software and it doesn't work when running software.py. It just says:

Cards on table:
Game stage: Prefloop

all the time. Any reason why and way to make it work currently?

**Comment by nowakowsky** [comment]
@CloneHub94 Sorry, this app won't work anymore. I've just created another one. Take a look at new one on my github, you may like it [Pokerstars-api](https://github.com/nowakowsky/Pokerstars-Api)
